version: "3.8"

services:
  node-1:
    build: .
    environment:
      - NODE_ROLE=Magistrate
      - PORT=3001
    ports:
      - "3001:3001"
    command: ["npm", "run", "simulate"]
  node-2:
    build: .
    environment:
      - NODE_ROLE=Scout
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - node-1
    command: ["npm", "run", "simulate"]
  node-3:
    build: .
    environment:
      - NODE_ROLE=Relay
      - PORT=3003
    ports:
      - "3003:3003"
    depends_on:
      - node-1
    command: ["npm", "run", "simulate"]
