export default function init(): Promise<any>;
export const IdentityCore: any;
export const AikidoCore: any;
export const SwarmNetwork: any;
export const EntropyBridge: any;
export const AikidoMath: any;
export const AcousticAnalyzer: any;
export const SwarmCore: any;
export const ProprioceptionCore: any;
export const CondorCluster: any;
export const VisionCore: any;
export const ArkManager: any;
export const MeshSurrogate: any;
